### ISSUE TITLE
'gulp build' returens Unhandled 'error' event

### ISSUE THREAD

**Issue by fazlerabbi37** [torifat/avro-pad#23]
Install went without a hitch whcih was done followed the [README](https://github.com/torifat/avro-pad/blob/master/README.md) but got the follwoing error when gave `sudo gulp build` command. 
```
[17:32:02] Using gulpfile /path/to/avro-pad/gulpfile.js
[17:32:02] Starting 'clean'...
[17:32:02] Finished 'clean' after 15 ms
[17:32:02] Starting 'images'...
[17:32:02] Finished 'images' after 14 ms
[17:32:02] Starting 'assets'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: /path/to/avro-pad/src/vendor/jquery.atwho/dist/css/jquery.atwho.css (if this was purposeful, use `allowEmpty` option)
    at DestroyableTransform.<anonymous> (/path/to/avro-pad/node_modules/gulp-useref/index.js:67:32)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at Pumpify.emit (events.js:211:7)
    at Pumpify.Duplexify._destroy (/path/to/avro-pad/node_modules/duplexify/index.js:191:15)
    at /path/to/avro-pad/node_modules/duplexify/index.js:182:10
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
running `sudo gulp` gives the same error message.

Worth mentioning after running `gulp watch` when http://localhost:8080/ in browser, following files failed to load:
- jquery.atwho.css
- jquery.js
- jquery.caret.js
- jquery.atwho.js
- jquery.autosize.js
- jquery.touchSwipe.js
- device.js

**Comment by sarim** [comment]
what is the output of `bower install` ? Are you familiar with bower? Bower has gone through some changes in their backend since this project was last updated. You probably have to adjust some of your local settings for bower to work.

why running with sudo?

**Comment by fazlerabbi37** [comment]
Output of ``bower install`` is `{}`. No, I am not familiar with bower.

---

Running `gulp build` and `gulp` without `sudo` gives the following output

```
[18:08:55] Using gulpfile /path/to/avro-pad/gulpfile.js
[18:08:55] Starting 'clean'...
[18:08:55] 'clean' errored after 4.16 ms
[18:08:55] Error: EACCES: permission denied, rmdir /path/to/avro-pad/build/images'
```

**Comment by sarim** [comment]
Can you delete your folder and try again, use this repo `https://github.com/omicronlab/avro-pad`

See this record for reference:
https://asciinema.org/a/KVl9dw6niTNFgVRGqgMbKxR6w

**Comment by fazlerabbi37** [comment]
`gulp watch` and `gulp build` works but `gulp` gives `Cannot GET /` error.

**Comment by sarim** [comment]
if gulp watch and gulp build works, then what else do you want gulp to do? :/

**Comment by fazlerabbi37** [comment]
I am sorry. I have no idea about JS, let alone NodeJS and `gulp`. I just followed the [README](https://github.com/torifat/avro-pad/blob/master/README.md) and in README is say's:
> This `$ gulp` command alone will do the above and also start a server with the production ready application. Open http://localhost:8888/ in your browser to test.
and that is what I was trying to achive :)
